use-grammars = { only = [ "cpp", "python", "haskell", "nix" ] }

[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "c", "h", "cppm"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "scheme"
language-servers = ["steel-language-server"]

[language-server.steel-language-server]
command = "steel-language-server"
args = []

[[language]]
name = "haskell"
language-servers = ["haskell-language-server"]

[language-server.haskell-language-server]
command = "haskell-language-server-wrapper"
args = ["--lsp"]
