[[language]]
name = "cpp"
file-types = ["cpp", "hpp", "c", "h", "cppm"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "scheme"
language-servers = ["steel-language-server"]

[language-server.steel-language-server]
command = "steel-language-server"
args = []
